version: '3'

services:
  osrm-backend-foot:
    image: activetravel-inverness/osrm-backend-foot
    build: ./osrm-backend-foot
    networks:
      - osrm

  osrm-backend-bicycle:
    image: activetravel-inverness/osrm-backend-bicycle
    build: ./osrm-backend-bicycle
    networks:
      - osrm

  osrm-nginx-reverse-proxy:
    image: activetravel-inverness/osrm-nginx-reverse-proxy
    build: ./osrm-nginx-reverse-proxy
    networks:
      - osrm
    ports:
      - "80:80"

networks:
  osrm:
    driver: overlay
